// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SearchMods() {
  return window['go']['main']['App']['SearchMods']();
}

export function StartWatcher() {
  return window['go']['main']['App']['StartWatcher']();
}

export function ToggleMod(arg1) {
  return window['go']['main']['App']['ToggleMod'](arg1);
}
