// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdates():Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function SearchMods():Promise<Array<main.Mod>>;

export function StartWatcher():Promise<void>;

export function ToggleMod(arg1:string):Promise<void>;
